#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

/* automatically generated by rust-bindgen */

pub const LIBIPMIMONITORING_VERSION_MAJOR: u32 = 1;
pub const LIBIPMIMONITORING_VERSION_MINOR: u32 = 0;
pub const LIBIPMIMONITORING_VERSION_PATCH: u32 = 9;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SUCCESS: ipmi_monitoring_error_codes = 0;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_CTX_NULL: ipmi_monitoring_error_codes = 1;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_CTX_INVALID: ipmi_monitoring_error_codes =
    2;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_PARAMETERS: ipmi_monitoring_error_codes =
    3;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_PERMISSION: ipmi_monitoring_error_codes =
    4;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_LIBRARY_UNINITIALIZED:
    ipmi_monitoring_error_codes = 5;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SEL_CONFIG_FILE_DOES_NOT_EXIST:
    ipmi_monitoring_error_codes = 6;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SEL_CONFIG_FILE_PARSE:
    ipmi_monitoring_error_codes = 7;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SENSOR_CONFIG_FILE_DOES_NOT_EXIST:
    ipmi_monitoring_error_codes = 8;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SENSOR_CONFIG_FILE_PARSE:
    ipmi_monitoring_error_codes = 9;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SDR_CACHE_PERMISSION:
    ipmi_monitoring_error_codes = 10;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SDR_CACHE_FILESYSTEM:
    ipmi_monitoring_error_codes = 11;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_HOSTNAME_INVALID:
    ipmi_monitoring_error_codes = 12;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SENSOR_NOT_FOUND:
    ipmi_monitoring_error_codes = 13;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_NO_SEL_RECORDS:
    ipmi_monitoring_error_codes = 14;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SEL_RECORDS_LIST_END:
    ipmi_monitoring_error_codes = 15;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SEL_RECORD_DATA_NOT_AVAILABLE:
    ipmi_monitoring_error_codes = 16;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_NO_SENSOR_READINGS:
    ipmi_monitoring_error_codes = 17;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SENSOR_READINGS_LIST_END:
    ipmi_monitoring_error_codes = 18;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_CONNECTION_TIMEOUT:
    ipmi_monitoring_error_codes = 19;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SESSION_TIMEOUT:
    ipmi_monitoring_error_codes = 20;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_USERNAME_INVALID:
    ipmi_monitoring_error_codes = 21;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_PASSWORD_INVALID:
    ipmi_monitoring_error_codes = 22;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_PASSWORD_VERIFICATION_TIMEOUT:
    ipmi_monitoring_error_codes = 23;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_K_G_INVALID: ipmi_monitoring_error_codes =
    24;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_PRIVILEGE_LEVEL_INSUFFICIENT:
    ipmi_monitoring_error_codes = 25;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_PRIVILEGEL_LEVEL_CANNOT_BE_OBTAINED:
    ipmi_monitoring_error_codes = 26;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_AUTHENTICATION_TYPE_UNAVAILABLE:
    ipmi_monitoring_error_codes = 27;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_IPMI_2_0_UNAVAILABLE:
    ipmi_monitoring_error_codes = 28;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_CIPHER_SUITE_ID_UNAVAILABLE:
    ipmi_monitoring_error_codes = 29;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_CALLBACK_ERROR:
    ipmi_monitoring_error_codes = 30;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_BMC_BUSY: ipmi_monitoring_error_codes =
    31;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_OUT_OF_MEMORY:
    ipmi_monitoring_error_codes = 32;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_IPMI_ERROR: ipmi_monitoring_error_codes =
    33;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_SYSTEM_ERROR:
    ipmi_monitoring_error_codes = 34;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_INTERNAL_ERROR:
    ipmi_monitoring_error_codes = 35;
pub const ipmi_monitoring_error_codes_IPMI_MONITORING_ERR_ERRNUMRANGE: ipmi_monitoring_error_codes =
    36;
pub type ipmi_monitoring_error_codes = u32;
pub const ipmi_monitoring_state_IPMI_MONITORING_STATE_NOMINAL: ipmi_monitoring_state = 0;
pub const ipmi_monitoring_state_IPMI_MONITORING_STATE_WARNING: ipmi_monitoring_state = 1;
pub const ipmi_monitoring_state_IPMI_MONITORING_STATE_CRITICAL: ipmi_monitoring_state = 2;
pub const ipmi_monitoring_state_IPMI_MONITORING_STATE_UNKNOWN: ipmi_monitoring_state = 3;
pub type ipmi_monitoring_state = u32;
pub const ipmi_monitoring_sel_record_type_class_IPMI_MONITORING_SEL_RECORD_TYPE_CLASS_SYSTEM_EVENT_RECORD : ipmi_monitoring_sel_record_type_class = 0 ;
pub const ipmi_monitoring_sel_record_type_class_IPMI_MONITORING_SEL_RECORD_TYPE_CLASS_TIMESTAMPED_OEM_RECORD : ipmi_monitoring_sel_record_type_class = 1 ;
pub const ipmi_monitoring_sel_record_type_class_IPMI_MONITORING_SEL_RECORD_TYPE_CLASS_NON_TIMESTAMPED_OEM_RECORD : ipmi_monitoring_sel_record_type_class = 2 ;
pub const ipmi_monitoring_sel_record_type_class_IPMI_MONITORING_SEL_RECORD_TYPE_CLASS_UNKNOWN:
    ipmi_monitoring_sel_record_type_class = 3;
pub type ipmi_monitoring_sel_record_type_class = u32;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_RESERVED:
    ipmi_monitoring_sensor_type = 0;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_TEMPERATURE:
    ipmi_monitoring_sensor_type = 1;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_VOLTAGE:
    ipmi_monitoring_sensor_type = 2;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_CURRENT:
    ipmi_monitoring_sensor_type = 3;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_FAN: ipmi_monitoring_sensor_type =
    4;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_PHYSICAL_SECURITY:
    ipmi_monitoring_sensor_type = 5;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_PLATFORM_SECURITY_VIOLATION_ATTEMPT : ipmi_monitoring_sensor_type = 6 ;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_PROCESSOR:
    ipmi_monitoring_sensor_type = 7;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_POWER_SUPPLY:
    ipmi_monitoring_sensor_type = 8;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_POWER_UNIT:
    ipmi_monitoring_sensor_type = 9;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_COOLING_DEVICE:
    ipmi_monitoring_sensor_type = 10;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_OTHER_UNITS_BASED_SENSOR:
    ipmi_monitoring_sensor_type = 11;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_MEMORY:
    ipmi_monitoring_sensor_type = 12;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_DRIVE_SLOT:
    ipmi_monitoring_sensor_type = 13;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_POST_MEMORY_RESIZE:
    ipmi_monitoring_sensor_type = 14;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS:
    ipmi_monitoring_sensor_type = 15;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_EVENT_LOGGING_DISABLED:
    ipmi_monitoring_sensor_type = 16;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_WATCHDOG1:
    ipmi_monitoring_sensor_type = 17;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_SYSTEM_EVENT:
    ipmi_monitoring_sensor_type = 18;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_CRITICAL_INTERRUPT:
    ipmi_monitoring_sensor_type = 19;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_BUTTON_SWITCH:
    ipmi_monitoring_sensor_type = 20;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_MODULE_BOARD:
    ipmi_monitoring_sensor_type = 21;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_MICROCONTROLLER_COPROCESSOR:
    ipmi_monitoring_sensor_type = 22;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_ADD_IN_CARD:
    ipmi_monitoring_sensor_type = 23;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_CHASSIS:
    ipmi_monitoring_sensor_type = 24;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_CHIP_SET:
    ipmi_monitoring_sensor_type = 25;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_OTHER_FRU:
    ipmi_monitoring_sensor_type = 26;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_CABLE_INTERCONNECT:
    ipmi_monitoring_sensor_type = 27;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_TERMINATOR:
    ipmi_monitoring_sensor_type = 28;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_SYSTEM_BOOT_INITIATED:
    ipmi_monitoring_sensor_type = 29;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_BOOT_ERROR:
    ipmi_monitoring_sensor_type = 30;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_OS_BOOT:
    ipmi_monitoring_sensor_type = 31;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_OS_CRITICAL_STOP:
    ipmi_monitoring_sensor_type = 32;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_SLOT_CONNECTOR:
    ipmi_monitoring_sensor_type = 33;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_SYSTEM_ACPI_POWER_STATE:
    ipmi_monitoring_sensor_type = 34;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_WATCHDOG2:
    ipmi_monitoring_sensor_type = 35;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_PLATFORM_ALERT:
    ipmi_monitoring_sensor_type = 36;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_ENTITY_PRESENCE:
    ipmi_monitoring_sensor_type = 37;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_MONITOR_ASIC_IC:
    ipmi_monitoring_sensor_type = 38;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_LAN: ipmi_monitoring_sensor_type =
    39;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_MANAGEMENT_SUBSYSTEM_HEALTH:
    ipmi_monitoring_sensor_type = 40;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_BATTERY:
    ipmi_monitoring_sensor_type = 41;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_SESSION_AUDIT:
    ipmi_monitoring_sensor_type = 42;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_VERSION_CHANGE:
    ipmi_monitoring_sensor_type = 43;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_FRU_STATE:
    ipmi_monitoring_sensor_type = 44;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_OEM_MIN:
    ipmi_monitoring_sensor_type = 192;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_OEM_MAX:
    ipmi_monitoring_sensor_type = 255;
pub const ipmi_monitoring_sensor_type_IPMI_MONITORING_SENSOR_TYPE_UNKNOWN:
    ipmi_monitoring_sensor_type = 65535;
pub type ipmi_monitoring_sensor_type = u32;
pub const ipmi_monitoring_sel_event_direction_IPMI_MONITORING_SEL_EVENT_DIRECTION_ASSERTION:
    ipmi_monitoring_sel_event_direction = 0;
pub const ipmi_monitoring_sel_event_direction_IPMI_MONITORING_SEL_EVENT_DIRECTION_DEASSERTION:
    ipmi_monitoring_sel_event_direction = 1;
pub type ipmi_monitoring_sel_event_direction = u32;
pub const ipmi_monitoring_sensor_units_IPMI_MONITORING_SENSOR_UNITS_NONE:
    ipmi_monitoring_sensor_units = 0;
pub const ipmi_monitoring_sensor_units_IPMI_MONITORING_SENSOR_UNITS_CELSIUS:
    ipmi_monitoring_sensor_units = 1;
pub const ipmi_monitoring_sensor_units_IPMI_MONITORING_SENSOR_UNITS_FAHRENHEIT:
    ipmi_monitoring_sensor_units = 2;
pub const ipmi_monitoring_sensor_units_IPMI_MONITORING_SENSOR_UNITS_VOLTS:
    ipmi_monitoring_sensor_units = 3;
pub const ipmi_monitoring_sensor_units_IPMI_MONITORING_SENSOR_UNITS_AMPS:
    ipmi_monitoring_sensor_units = 4;
pub const ipmi_monitoring_sensor_units_IPMI_MONITORING_SENSOR_UNITS_RPM:
    ipmi_monitoring_sensor_units = 5;
pub const ipmi_monitoring_sensor_units_IPMI_MONITORING_SENSOR_UNITS_WATTS:
    ipmi_monitoring_sensor_units = 6;
pub const ipmi_monitoring_sensor_units_IPMI_MONITORING_SENSOR_UNITS_PERCENT:
    ipmi_monitoring_sensor_units = 7;
pub const ipmi_monitoring_sensor_units_IPMI_MONITORING_SENSOR_UNITS_UNKNOWN:
    ipmi_monitoring_sensor_units = 255;
pub type ipmi_monitoring_sensor_units = u32;
pub const ipmi_monitoring_sensor_reading_type_IPMI_MONITORING_SENSOR_READING_TYPE_UNSIGNED_INTEGER8_BOOL : ipmi_monitoring_sensor_reading_type = 0 ;
pub const ipmi_monitoring_sensor_reading_type_IPMI_MONITORING_SENSOR_READING_TYPE_UNSIGNED_INTEGER32 : ipmi_monitoring_sensor_reading_type = 1 ;
pub const ipmi_monitoring_sensor_reading_type_IPMI_MONITORING_SENSOR_READING_TYPE_DOUBLE:
    ipmi_monitoring_sensor_reading_type = 2;
pub const ipmi_monitoring_sensor_reading_type_IPMI_MONITORING_SENSOR_READING_TYPE_UNKNOWN:
    ipmi_monitoring_sensor_reading_type = 255;
pub type ipmi_monitoring_sensor_reading_type = u32;
pub const ipmi_monitoring_driver_type_IPMI_MONITORING_DRIVER_TYPE_KCS: ipmi_monitoring_driver_type =
    0;
pub const ipmi_monitoring_driver_type_IPMI_MONITORING_DRIVER_TYPE_SSIF:
    ipmi_monitoring_driver_type = 1;
pub const ipmi_monitoring_driver_type_IPMI_MONITORING_DRIVER_TYPE_OPENIPMI:
    ipmi_monitoring_driver_type = 2;
pub const ipmi_monitoring_driver_type_IPMI_MONITORING_DRIVER_TYPE_SUNBMC:
    ipmi_monitoring_driver_type = 3;
pub type ipmi_monitoring_driver_type = u32;
pub const ipmi_monitoring_protocol_version_IPMI_MONITORING_PROTOCOL_VERSION_1_5:
    ipmi_monitoring_protocol_version = 0;
pub const ipmi_monitoring_protocol_version_IPMI_MONITORING_PROTOCOL_VERSION_2_0:
    ipmi_monitoring_protocol_version = 1;
pub type ipmi_monitoring_protocol_version = u32;
pub const ipmi_monitoring_privilege_IPMI_MONITORING_PRIVILEGE_LEVEL_USER:
    ipmi_monitoring_privilege = 0;
pub const ipmi_monitoring_privilege_IPMI_MONITORING_PRIVILEGE_LEVEL_OPERATOR:
    ipmi_monitoring_privilege = 1;
pub const ipmi_monitoring_privilege_IPMI_MONITORING_PRIVILEGE_LEVEL_ADMIN:
    ipmi_monitoring_privilege = 2;
pub type ipmi_monitoring_privilege = u32;
pub const ipmi_monitoring_authentication_type_IPMI_MONITORING_AUTHENTICATION_TYPE_NONE:
    ipmi_monitoring_authentication_type = 0;
pub const ipmi_monitoring_authentication_type_IPMI_MONITORING_AUTHENTICATION_TYPE_STRAIGHT_PASSWORD_KEY : ipmi_monitoring_authentication_type = 1 ;
pub const ipmi_monitoring_authentication_type_IPMI_MONITORING_AUTHENTICATION_TYPE_MD2:
    ipmi_monitoring_authentication_type = 2;
pub const ipmi_monitoring_authentication_type_IPMI_MONITORING_AUTHENTICATION_TYPE_MD5:
    ipmi_monitoring_authentication_type = 3;
pub type ipmi_monitoring_authentication_type = u32;
pub const ipmi_monitoring_flags_IPMI_MONITORING_FLAGS_NONE: ipmi_monitoring_flags = 0;
pub const ipmi_monitoring_flags_IPMI_MONITORING_FLAGS_DEBUG: ipmi_monitoring_flags = 1;
pub const ipmi_monitoring_flags_IPMI_MONITORING_FLAGS_DEBUG_IPMI_PACKETS: ipmi_monitoring_flags = 2;
pub const ipmi_monitoring_flags_IPMI_MONITORING_FLAGS_LOCK_MEMORY: ipmi_monitoring_flags = 4;
pub type ipmi_monitoring_flags = u32;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_1_5_AUTHENTICATION_CAPABILITIES : ipmi_monitoring_workaround_flags = 1 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_1_5_ACCEPT_SESSION_ID_ZERO : ipmi_monitoring_workaround_flags = 2 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_1_5_FORCE_PERMSG_AUTHENTICATION : ipmi_monitoring_workaround_flags = 4 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_1_5_CHECK_UNEXPECTED_AUTHCODE : ipmi_monitoring_workaround_flags = 8 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_1_5_BIG_ENDIAN_SEQUENCE_NUMBER : ipmi_monitoring_workaround_flags = 16 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_1_5_NO_AUTH_CODE_CHECK : ipmi_monitoring_workaround_flags = 32 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_1_5_NO_CHECKSUM_CHECK : ipmi_monitoring_workaround_flags = 64 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_2_0_AUTHENTICATION_CAPABILITIES : ipmi_monitoring_workaround_flags = 1 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_2_0_INTEL_2_0_SESSION : ipmi_monitoring_workaround_flags = 2 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_2_0_SUPERMICRO_2_0_SESSION : ipmi_monitoring_workaround_flags = 4 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_2_0_SUN_2_0_SESSION : ipmi_monitoring_workaround_flags = 8 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_2_0_OPEN_SESSION_PRIVILEGE : ipmi_monitoring_workaround_flags = 16 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_2_0_NON_EMPTY_INTEGRITY_CHECK_VALUE : ipmi_monitoring_workaround_flags = 32 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_PROTOCOL_VERSION_2_0_NO_CHECKSUM_CHECK : ipmi_monitoring_workaround_flags = 64 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_INBAND_ASSUME_IO_BASE_ADDRESS : ipmi_monitoring_workaround_flags = 1 ;
pub const ipmi_monitoring_workaround_flags_IPMI_MONITORING_WORKAROUND_FLAGS_INBAND_SPIN_POLL:
    ipmi_monitoring_workaround_flags = 2;
pub type ipmi_monitoring_workaround_flags = u32;
pub const ipmi_monitoring_sel_flags_IPMI_MONITORING_SEL_FLAGS_REREAD_SDR_CACHE:
    ipmi_monitoring_sel_flags = 1;
pub const ipmi_monitoring_sel_flags_IPMI_MONITORING_SEL_FLAGS_INTERPRET_OEM_DATA:
    ipmi_monitoring_sel_flags = 2;
pub const ipmi_monitoring_sel_flags_IPMI_MONITORING_SEL_FLAGS_ASSUME_SYSTEM_EVENT_RECORD:
    ipmi_monitoring_sel_flags = 4;
pub const ipmi_monitoring_sel_flags_IPMI_MONITORING_SEL_FLAGS_ENTITY_SENSOR_NAMES:
    ipmi_monitoring_sel_flags = 8;
pub const ipmi_monitoring_sel_flags_IPMI_MONITORING_SEL_FLAGS_ASSUME_MAX_SDR_RECORD_COUNT:
    ipmi_monitoring_sel_flags = 16;
pub type ipmi_monitoring_sel_flags = u32;
pub const ipmi_monitoring_sensor_reading_flags_IPMI_MONITORING_SENSOR_READING_FLAGS_REREAD_SDR_CACHE : ipmi_monitoring_sensor_reading_flags = 1 ;
pub const ipmi_monitoring_sensor_reading_flags_IPMI_MONITORING_SENSOR_READING_FLAGS_IGNORE_NON_INTERPRETABLE_SENSORS : ipmi_monitoring_sensor_reading_flags = 2 ;
pub const ipmi_monitoring_sensor_reading_flags_IPMI_MONITORING_SENSOR_READING_FLAGS_BRIDGE_SENSORS : ipmi_monitoring_sensor_reading_flags = 4 ;
pub const ipmi_monitoring_sensor_reading_flags_IPMI_MONITORING_SENSOR_READING_FLAGS_INTERPRET_OEM_DATA : ipmi_monitoring_sensor_reading_flags = 8 ;
pub const ipmi_monitoring_sensor_reading_flags_IPMI_MONITORING_SENSOR_READING_FLAGS_SHARED_SENSORS : ipmi_monitoring_sensor_reading_flags = 16 ;
pub const ipmi_monitoring_sensor_reading_flags_IPMI_MONITORING_SENSOR_READING_FLAGS_DISCRETE_READING : ipmi_monitoring_sensor_reading_flags = 32 ;
pub const ipmi_monitoring_sensor_reading_flags_IPMI_MONITORING_SENSOR_READING_FLAGS_IGNORE_SCANNING_DISABLED : ipmi_monitoring_sensor_reading_flags = 64 ;
pub const ipmi_monitoring_sensor_reading_flags_IPMI_MONITORING_SENSOR_READING_FLAGS_ASSUME_BMC_OWNER : ipmi_monitoring_sensor_reading_flags = 128 ;
pub const ipmi_monitoring_sensor_reading_flags_IPMI_MONITORING_SENSOR_READING_FLAGS_ENTITY_SENSOR_NAMES : ipmi_monitoring_sensor_reading_flags = 256 ;
pub const ipmi_monitoring_sensor_reading_flags_IPMI_MONITORING_SENSOR_READING_FLAGS_ASSUME_MAX_SDR_RECORD_COUNT : ipmi_monitoring_sensor_reading_flags = 512 ;
pub const ipmi_monitoring_sensor_reading_flags_IPMI_MONITORING_SENSOR_READING_FLAGS_IGNORE_UNREADABLE_SENSORS : ipmi_monitoring_sensor_reading_flags = 2 ;
pub type ipmi_monitoring_sensor_reading_flags = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ipmi_monitoring_ipmi_config {
    pub driver_type: ::std::os::raw::c_int,
    pub disable_auto_probe: ::std::os::raw::c_int,
    pub driver_address: ::std::os::raw::c_uint,
    pub register_spacing: ::std::os::raw::c_uint,
    pub driver_device: *mut ::std::os::raw::c_char,
    pub protocol_version: ::std::os::raw::c_int,
    pub username: *mut ::std::os::raw::c_char,
    pub password: *mut ::std::os::raw::c_char,
    pub k_g: *mut ::std::os::raw::c_uchar,
    pub k_g_len: ::std::os::raw::c_uint,
    pub privilege_level: ::std::os::raw::c_int,
    pub authentication_type: ::std::os::raw::c_int,
    pub cipher_suite_id: ::std::os::raw::c_int,
    pub session_timeout_len: ::std::os::raw::c_int,
    pub retransmission_timeout_len: ::std::os::raw::c_int,
    pub workaround_flags: ::std::os::raw::c_uint,
}
#[test]
fn bindgen_test_layout_ipmi_monitoring_ipmi_config() {
    assert_eq!(
        ::std::mem::size_of::<ipmi_monitoring_ipmi_config>(),
        88usize,
        concat!("Size of: ", stringify!(ipmi_monitoring_ipmi_config))
    );
    assert_eq!(
        ::std::mem::align_of::<ipmi_monitoring_ipmi_config>(),
        8usize,
        concat!("Alignment of ", stringify!(ipmi_monitoring_ipmi_config))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).driver_type as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(driver_type)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).disable_auto_probe as *const _
                as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(disable_auto_probe)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).driver_address as *const _
                as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(driver_address)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).register_spacing as *const _
                as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(register_spacing)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).driver_device as *const _
                as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(driver_device)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).protocol_version as *const _
                as usize
        },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(protocol_version)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).username as *const _ as usize
        },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(username)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).password as *const _ as usize
        },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(password)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).k_g as *const _ as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(k_g)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).k_g_len as *const _ as usize
        },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(k_g_len)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).privilege_level as *const _
                as usize
        },
        60usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(privilege_level)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).authentication_type as *const _
                as usize
        },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(authentication_type)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).cipher_suite_id as *const _
                as usize
        },
        68usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(cipher_suite_id)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).session_timeout_len as *const _
                as usize
        },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(session_timeout_len)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).retransmission_timeout_len
                as *const _ as usize
        },
        76usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(retransmission_timeout_len)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<ipmi_monitoring_ipmi_config>())).workaround_flags as *const _
                as usize
        },
        80usize,
        concat!(
            "Offset of field: ",
            stringify!(ipmi_monitoring_ipmi_config),
            "::",
            stringify!(workaround_flags)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ipmi_monitoring_ctx {
    _unused: [u8; 0],
}
pub type ipmi_monitoring_ctx_t = *mut ipmi_monitoring_ctx;
pub type Ipmi_Monitoring_Callback = ::std::option::Option<
    unsafe extern "C" fn(
        c: ipmi_monitoring_ctx_t,
        callback_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
extern "C" {
    pub fn ipmi_monitoring_init(
        flags: ::std::os::raw::c_uint,
        errnum: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_ctx_create() -> ipmi_monitoring_ctx_t;
}
extern "C" {
    pub fn ipmi_monitoring_ctx_destroy(c: ipmi_monitoring_ctx_t);
}
extern "C" {
    pub fn ipmi_monitoring_ctx_errnum(c: ipmi_monitoring_ctx_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_ctx_strerror(
        errnum: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn ipmi_monitoring_ctx_errormsg(c: ipmi_monitoring_ctx_t) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn ipmi_monitoring_ctx_sel_config_file(
        c: ipmi_monitoring_ctx_t,
        sel_config_file: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_ctx_sensor_config_file(
        c: ipmi_monitoring_ctx_t,
        sensor_config_file: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_ctx_sdr_cache_directory(
        c: ipmi_monitoring_ctx_t,
        dir: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_ctx_sdr_cache_filenames(
        c: ipmi_monitoring_ctx_t,
        format: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_by_record_id(
        c: ipmi_monitoring_ctx_t,
        hostname: *const ::std::os::raw::c_char,
        config: *mut ipmi_monitoring_ipmi_config,
        sel_flags: ::std::os::raw::c_uint,
        record_ids: *mut ::std::os::raw::c_uint,
        record_ids_len: ::std::os::raw::c_uint,
        callback: Ipmi_Monitoring_Callback,
        callback_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_by_sensor_type(
        c: ipmi_monitoring_ctx_t,
        hostname: *const ::std::os::raw::c_char,
        config: *mut ipmi_monitoring_ipmi_config,
        sel_flags: ::std::os::raw::c_uint,
        sensor_types: *mut ::std::os::raw::c_uint,
        sensor_types_len: ::std::os::raw::c_uint,
        callback: Ipmi_Monitoring_Callback,
        callback_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_by_date_range(
        c: ipmi_monitoring_ctx_t,
        hostname: *const ::std::os::raw::c_char,
        config: *mut ipmi_monitoring_ipmi_config,
        sel_flags: ::std::os::raw::c_uint,
        date_begin: *const ::std::os::raw::c_char,
        date_end: *const ::std::os::raw::c_char,
        callback: Ipmi_Monitoring_Callback,
        callback_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_iterator_first(c: ipmi_monitoring_ctx_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_iterator_next(c: ipmi_monitoring_ctx_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_iterator_destroy(c: ipmi_monitoring_ctx_t);
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_record_id(c: ipmi_monitoring_ctx_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_record_type(c: ipmi_monitoring_ctx_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_record_type_class(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_sel_state(c: ipmi_monitoring_ctx_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_timestamp(
        c: ipmi_monitoring_ctx_t,
        timestamp: *mut ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_sensor_type(c: ipmi_monitoring_ctx_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_sensor_number(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_sensor_name(
        c: ipmi_monitoring_ctx_t,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_event_direction(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_event_offset_type(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_event_offset(c: ipmi_monitoring_ctx_t)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_event_offset_string(
        c: ipmi_monitoring_ctx_t,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_event_type_code(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_event_data(
        c: ipmi_monitoring_ctx_t,
        event_data1: *mut ::std::os::raw::c_uint,
        event_data2: *mut ::std::os::raw::c_uint,
        event_data3: *mut ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_manufacturer_id(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sel_read_oem_data(
        c: ipmi_monitoring_ctx_t,
        oem_data: *mut ::std::os::raw::c_void,
        oem_data_len: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_readings_by_record_id(
        c: ipmi_monitoring_ctx_t,
        hostname: *const ::std::os::raw::c_char,
        config: *mut ipmi_monitoring_ipmi_config,
        sensor_reading_flags: ::std::os::raw::c_uint,
        record_ids: *mut ::std::os::raw::c_uint,
        record_ids_len: ::std::os::raw::c_uint,
        callback: Ipmi_Monitoring_Callback,
        callback_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_readings_by_sensor_type(
        c: ipmi_monitoring_ctx_t,
        hostname: *const ::std::os::raw::c_char,
        config: *mut ipmi_monitoring_ipmi_config,
        sensor_reading_flags: ::std::os::raw::c_uint,
        sensor_types: *mut ::std::os::raw::c_uint,
        sensor_types_len: ::std::os::raw::c_uint,
        callback: Ipmi_Monitoring_Callback,
        callback_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_iterator_first(c: ipmi_monitoring_ctx_t)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_iterator_next(c: ipmi_monitoring_ctx_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_iterator_destroy(c: ipmi_monitoring_ctx_t);
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_record_id(c: ipmi_monitoring_ctx_t)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_sensor_number(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_sensor_type(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_sensor_name(
        c: ipmi_monitoring_ctx_t,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_sensor_state(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_sensor_units(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_sensor_reading_type(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_sensor_reading(
        c: ipmi_monitoring_ctx_t,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_sensor_bitmask_type(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_sensor_bitmask(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_sensor_bitmask_strings(
        c: ipmi_monitoring_ctx_t,
    ) -> *mut *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn ipmi_monitoring_sensor_read_event_reading_type_code(
        c: ipmi_monitoring_ctx_t,
    ) -> ::std::os::raw::c_int;
}
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_THRESHOLD:
    ipmi_monitoring_sensor_bitmask_type = 0;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_TRANSITION_STATE : ipmi_monitoring_sensor_bitmask_type = 1 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_STATE:
    ipmi_monitoring_sensor_bitmask_type = 2;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_PREDICTIVE_FAILURE : ipmi_monitoring_sensor_bitmask_type = 3 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_LIMIT:
    ipmi_monitoring_sensor_bitmask_type = 4;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_PERFORMANCE:
    ipmi_monitoring_sensor_bitmask_type = 5;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_TRANSITION_SEVERITY : ipmi_monitoring_sensor_bitmask_type = 6 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_DEVICE_PRESENT:
    ipmi_monitoring_sensor_bitmask_type = 7;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_DEVICE_ENABLED:
    ipmi_monitoring_sensor_bitmask_type = 8;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_TRANSITION_AVAILABILITY : ipmi_monitoring_sensor_bitmask_type = 9 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_REDUNDANCY:
    ipmi_monitoring_sensor_bitmask_type = 10;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_ACPI_POWER_STATE : ipmi_monitoring_sensor_bitmask_type = 11 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_PHYSICAL_SECURITY : ipmi_monitoring_sensor_bitmask_type = 12 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_PLATFORM_SECURITY_VIOLATION_ATTEMPT : ipmi_monitoring_sensor_bitmask_type = 13 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_PROCESSOR:
    ipmi_monitoring_sensor_bitmask_type = 14;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_POWER_SUPPLY:
    ipmi_monitoring_sensor_bitmask_type = 15;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_POWER_UNIT:
    ipmi_monitoring_sensor_bitmask_type = 16;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_COOLING_DEVICE:
    ipmi_monitoring_sensor_bitmask_type = 17;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_OTHER_UNITS_BASED_SENSOR : ipmi_monitoring_sensor_bitmask_type = 18 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_MEMORY:
    ipmi_monitoring_sensor_bitmask_type = 19;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_DRIVE_SLOT:
    ipmi_monitoring_sensor_bitmask_type = 20;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_POST_MEMORY_RESIZE : ipmi_monitoring_sensor_bitmask_type = 21 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_SYSTEM_FIRMWARE_PROGRESS : ipmi_monitoring_sensor_bitmask_type = 22 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_EVENT_LOGGING_DISABLED : ipmi_monitoring_sensor_bitmask_type = 23 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_WATCHDOG1:
    ipmi_monitoring_sensor_bitmask_type = 24;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_SYSTEM_EVENT:
    ipmi_monitoring_sensor_bitmask_type = 25;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_CRITICAL_INTERRUPT : ipmi_monitoring_sensor_bitmask_type = 26 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_BUTTON_SWITCH:
    ipmi_monitoring_sensor_bitmask_type = 27;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_MODULE_BOARD:
    ipmi_monitoring_sensor_bitmask_type = 28;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_MICROCONTROLLER_COPROCESSOR : ipmi_monitoring_sensor_bitmask_type = 29 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_ADD_IN_CARD:
    ipmi_monitoring_sensor_bitmask_type = 30;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_CHASSIS:
    ipmi_monitoring_sensor_bitmask_type = 31;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_CHIP_SET:
    ipmi_monitoring_sensor_bitmask_type = 32;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_OTHER_FRU:
    ipmi_monitoring_sensor_bitmask_type = 33;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_CABLE_INTERCONNECT : ipmi_monitoring_sensor_bitmask_type = 34 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_TERMINATOR:
    ipmi_monitoring_sensor_bitmask_type = 35;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_SYSTEM_BOOT_INITIATED : ipmi_monitoring_sensor_bitmask_type = 36 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_BOOT_ERROR:
    ipmi_monitoring_sensor_bitmask_type = 37;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_OS_BOOT:
    ipmi_monitoring_sensor_bitmask_type = 38;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_OS_CRITICAL_STOP : ipmi_monitoring_sensor_bitmask_type = 39 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_SLOT_CONNECTOR:
    ipmi_monitoring_sensor_bitmask_type = 40;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_SYSTEM_ACPI_POWER_STATE : ipmi_monitoring_sensor_bitmask_type = 41 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_WATCHDOG2:
    ipmi_monitoring_sensor_bitmask_type = 42;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_PLATFORM_ALERT:
    ipmi_monitoring_sensor_bitmask_type = 43;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_ENTITY_PRESENCE : ipmi_monitoring_sensor_bitmask_type = 44 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_MONITOR_ASIC_IC : ipmi_monitoring_sensor_bitmask_type = 45 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_LAN:
    ipmi_monitoring_sensor_bitmask_type = 46;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_MANAGEMENT_SUBSYSTEM_HEALTH : ipmi_monitoring_sensor_bitmask_type = 47 ;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_BATTERY:
    ipmi_monitoring_sensor_bitmask_type = 48;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_SESSION_AUDIT:
    ipmi_monitoring_sensor_bitmask_type = 49;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_VERSION_CHANGE:
    ipmi_monitoring_sensor_bitmask_type = 50;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_FRU_STATE:
    ipmi_monitoring_sensor_bitmask_type = 51;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_OEM:
    ipmi_monitoring_sensor_bitmask_type = 254;
pub const ipmi_monitoring_sensor_bitmask_type_IPMI_MONITORING_SENSOR_BITMASK_TYPE_UNKNOWN:
    ipmi_monitoring_sensor_bitmask_type = 255;
pub type ipmi_monitoring_sensor_bitmask_type = u32;
pub const ipmi_monitoring_sensor_bitmask_threshold_IPMI_MONITORING_SENSOR_BITMASK_THRESHOLD_AT_OR_BELOW_LOWER_NON_CRITICAL_THRESHOLD : ipmi_monitoring_sensor_bitmask_threshold = 1 ;
pub const ipmi_monitoring_sensor_bitmask_threshold_IPMI_MONITORING_SENSOR_BITMASK_THRESHOLD_AT_OR_BELOW_LOWER_CRITICAL_THRESHOLD : ipmi_monitoring_sensor_bitmask_threshold = 2 ;
pub const ipmi_monitoring_sensor_bitmask_threshold_IPMI_MONITORING_SENSOR_BITMASK_THRESHOLD_AT_OR_BELOW_LOWER_NON_RECOVERABLE_THRESHOLD : ipmi_monitoring_sensor_bitmask_threshold = 4 ;
pub const ipmi_monitoring_sensor_bitmask_threshold_IPMI_MONITORING_SENSOR_BITMASK_THRESHOLD_AT_OR_BELOW_UPPER_NON_CRITICAL_THRESHOLD : ipmi_monitoring_sensor_bitmask_threshold = 8 ;
pub const ipmi_monitoring_sensor_bitmask_threshold_IPMI_MONITORING_SENSOR_BITMASK_THRESHOLD_AT_OR_BELOW_UPPER_CRITICAL_THRESHOLD : ipmi_monitoring_sensor_bitmask_threshold = 16 ;
pub const ipmi_monitoring_sensor_bitmask_threshold_IPMI_MONITORING_SENSOR_BITMASK_THRESHOLD_AT_OR_BELOW_UPPER_NON_RECOVERABLE_THRESHOLD : ipmi_monitoring_sensor_bitmask_threshold = 32 ;
pub type ipmi_monitoring_sensor_bitmask_threshold = u32;
pub const ipmi_monitoring_sensor_bitmask_transition_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_IDLE : ipmi_monitoring_sensor_bitmask_transition = 1 ;
pub const ipmi_monitoring_sensor_bitmask_transition_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_ACTIVE : ipmi_monitoring_sensor_bitmask_transition = 2 ;
pub const ipmi_monitoring_sensor_bitmask_transition_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_BUSY : ipmi_monitoring_sensor_bitmask_transition = 4 ;
pub type ipmi_monitoring_sensor_bitmask_transition = u32;
pub const ipmi_monitoring_sensor_bitmask_state_IPMI_MONITORING_SENSOR_BITMASK_STATE_DEASSERTED:
    ipmi_monitoring_sensor_bitmask_state = 1;
pub const ipmi_monitoring_sensor_bitmask_state_IPMI_MONITORING_SENSOR_BITMASK_STATE_ASSERTED:
    ipmi_monitoring_sensor_bitmask_state = 2;
pub type ipmi_monitoring_sensor_bitmask_state = u32;
pub const ipmi_monitoring_sensor_bitmask_predictive_failure_IPMI_MONITORING_SENSOR_BITMASK_PREDICTIVE_FAILURE_DEASSERTED : ipmi_monitoring_sensor_bitmask_predictive_failure = 1 ;
pub const ipmi_monitoring_sensor_bitmask_predictive_failure_IPMI_MONITORING_SENSOR_BITMASK_PREDICTIVE_FAILURE_ASSERTED : ipmi_monitoring_sensor_bitmask_predictive_failure = 2 ;
pub type ipmi_monitoring_sensor_bitmask_predictive_failure = u32;
pub const ipmi_monitoring_sensor_bitmask_limit_IPMI_MONITORING_SENSOR_BITMASK_LIMIT_NOT_EXCEEDED:
    ipmi_monitoring_sensor_bitmask_limit = 1;
pub const ipmi_monitoring_sensor_bitmask_limit_IPMI_MONITORING_SENSOR_BITMASK_LIMIT_EXCEEDED:
    ipmi_monitoring_sensor_bitmask_limit = 2;
pub type ipmi_monitoring_sensor_bitmask_limit = u32;
pub const ipmi_monitoring_sensor_bitmask_performance_IPMI_MONITORING_SENSOR_BITMASK_PERFORMANCE_MET : ipmi_monitoring_sensor_bitmask_performance = 1 ;
pub const ipmi_monitoring_sensor_bitmask_performance_IPMI_MONITORING_SENSOR_BITMASK_PERFORMANCE_LAGS : ipmi_monitoring_sensor_bitmask_performance = 2 ;
pub type ipmi_monitoring_sensor_bitmask_performance = u32;
pub const ipmi_monitoring_sensor_bitmask_transition_severity_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_OK : ipmi_monitoring_sensor_bitmask_transition_severity = 1 ;
pub const ipmi_monitoring_sensor_bitmask_transition_severity_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_NON_CRITICAL_FROM_OK : ipmi_monitoring_sensor_bitmask_transition_severity = 2 ;
pub const ipmi_monitoring_sensor_bitmask_transition_severity_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_CRITICAL_FROM_LESS_SEVERE : ipmi_monitoring_sensor_bitmask_transition_severity = 4 ;
pub const ipmi_monitoring_sensor_bitmask_transition_severity_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_NON_RECOVERABLE_FROM_LESS_SEVERE : ipmi_monitoring_sensor_bitmask_transition_severity = 8 ;
pub const ipmi_monitoring_sensor_bitmask_transition_severity_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_NON_CRITICAL_FROM_MORE_SEVERE : ipmi_monitoring_sensor_bitmask_transition_severity = 16 ;
pub const ipmi_monitoring_sensor_bitmask_transition_severity_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_CRITICAL_FROM_NON_RECOVERABLE : ipmi_monitoring_sensor_bitmask_transition_severity = 32 ;
pub const ipmi_monitoring_sensor_bitmask_transition_severity_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_NON_RECOVERABLE : ipmi_monitoring_sensor_bitmask_transition_severity = 64 ;
pub const ipmi_monitoring_sensor_bitmask_transition_severity_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_MONITOR : ipmi_monitoring_sensor_bitmask_transition_severity = 128 ;
pub const ipmi_monitoring_sensor_bitmask_transition_severity_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_INFORMATIONAL : ipmi_monitoring_sensor_bitmask_transition_severity = 256 ;
pub type ipmi_monitoring_sensor_bitmask_transition_severity = u32;
pub const ipmi_monitoring_sensor_bitmask_device_present_IPMI_MONITORING_SENSOR_BITMASK_DEVICE_REMOVED_DEVICE_ABSENT : ipmi_monitoring_sensor_bitmask_device_present = 1 ;
pub const ipmi_monitoring_sensor_bitmask_device_present_IPMI_MONITORING_SENSOR_BITMASK_DEVICE_INSERTED_DEVICE_PRESENT : ipmi_monitoring_sensor_bitmask_device_present = 2 ;
pub type ipmi_monitoring_sensor_bitmask_device_present = u32;
pub const ipmi_monitoring_sensor_bitmask_device_enabled_IPMI_MONITORING_SENSOR_BITMASK_DEVICE_DISABLED : ipmi_monitoring_sensor_bitmask_device_enabled = 1 ;
pub const ipmi_monitoring_sensor_bitmask_device_enabled_IPMI_MONITORING_SENSOR_BITMASK_DEVICE_ENABLED : ipmi_monitoring_sensor_bitmask_device_enabled = 2 ;
pub type ipmi_monitoring_sensor_bitmask_device_enabled = u32;
pub const ipmi_monitoring_sensor_bitmask_transition_availability_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_RUNNING : ipmi_monitoring_sensor_bitmask_transition_availability = 1 ;
pub const ipmi_monitoring_sensor_bitmask_transition_availability_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_IN_TEST : ipmi_monitoring_sensor_bitmask_transition_availability = 2 ;
pub const ipmi_monitoring_sensor_bitmask_transition_availability_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_POWER_OFF : ipmi_monitoring_sensor_bitmask_transition_availability = 4 ;
pub const ipmi_monitoring_sensor_bitmask_transition_availability_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_ON_LINE : ipmi_monitoring_sensor_bitmask_transition_availability = 8 ;
pub const ipmi_monitoring_sensor_bitmask_transition_availability_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_OFF_LINE : ipmi_monitoring_sensor_bitmask_transition_availability = 16 ;
pub const ipmi_monitoring_sensor_bitmask_transition_availability_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_OFF_DUTY : ipmi_monitoring_sensor_bitmask_transition_availability = 32 ;
pub const ipmi_monitoring_sensor_bitmask_transition_availability_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_DEGRADED : ipmi_monitoring_sensor_bitmask_transition_availability = 64 ;
pub const ipmi_monitoring_sensor_bitmask_transition_availability_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_TO_POWER_SAVE : ipmi_monitoring_sensor_bitmask_transition_availability = 128 ;
pub const ipmi_monitoring_sensor_bitmask_transition_availability_IPMI_MONITORING_SENSOR_BITMASK_TRANSITION_INSTALL_ERROR : ipmi_monitoring_sensor_bitmask_transition_availability = 256 ;
pub type ipmi_monitoring_sensor_bitmask_transition_availability = u32;
pub const ipmi_monitoring_sensor_bitmask_redundancy_IPMI_MONITORING_SENSOR_BITMASK_FULLY_REDUNDANT : ipmi_monitoring_sensor_bitmask_redundancy = 1 ;
pub const ipmi_monitoring_sensor_bitmask_redundancy_IPMI_MONITORING_SENSOR_BITMASK_REDUNDANCY_LOST : ipmi_monitoring_sensor_bitmask_redundancy = 2 ;
pub const ipmi_monitoring_sensor_bitmask_redundancy_IPMI_MONITORING_SENSOR_BITMASK_REDUNDANCY_DEGRADED : ipmi_monitoring_sensor_bitmask_redundancy = 4 ;
pub const ipmi_monitoring_sensor_bitmask_redundancy_IPMI_MONITORING_SENSOR_BITMASK_NON_REDUNDANT_SUFFICIENT_RESOURCES_FROM_REDUNDANT : ipmi_monitoring_sensor_bitmask_redundancy = 8 ;
pub const ipmi_monitoring_sensor_bitmask_redundancy_IPMI_MONITORING_SENSOR_BITMASK_NON_REDUNDANT_SUFFICIENT_RESOURCES_FROM_INSUFFICIENT_RESOURCES : ipmi_monitoring_sensor_bitmask_redundancy = 16 ;
pub const ipmi_monitoring_sensor_bitmask_redundancy_IPMI_MONITORING_SENSOR_BITMASK_NON_REDUNDANT_INSUFFICIENT_RESOURCES : ipmi_monitoring_sensor_bitmask_redundancy = 32 ;
pub const ipmi_monitoring_sensor_bitmask_redundancy_IPMI_MONITORING_SENSOR_BITMASK_REDUNDANCY_DEGRADED_FROM_FULLY_REDUNDANT : ipmi_monitoring_sensor_bitmask_redundancy = 64 ;
pub const ipmi_monitoring_sensor_bitmask_redundancy_IPMI_MONITORING_SENSOR_BITMASK_REDUNDANCY_DEGRADED_FROM_NON_REDUNDANT : ipmi_monitoring_sensor_bitmask_redundancy = 128 ;
pub type ipmi_monitoring_sensor_bitmask_redundancy = u32;
pub const ipmi_monitoring_sensor_bitmask_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_D0_POWER_STATE : ipmi_monitoring_sensor_bitmask_acpi_power_state = 1 ;
pub const ipmi_monitoring_sensor_bitmask_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_D1_POWER_STATE : ipmi_monitoring_sensor_bitmask_acpi_power_state = 2 ;
pub const ipmi_monitoring_sensor_bitmask_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_D2_POWER_STATE : ipmi_monitoring_sensor_bitmask_acpi_power_state = 4 ;
pub const ipmi_monitoring_sensor_bitmask_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_D3_POWER_STATE : ipmi_monitoring_sensor_bitmask_acpi_power_state = 8 ;
pub type ipmi_monitoring_sensor_bitmask_acpi_power_state = u32;
pub const ipmi_monitoring_sensor_bitmask_physical_security_IPMI_MONITORING_SENSOR_BITMASK_PHYSICAL_SECURITY_GENERAL_CHASSIS_INTRUSION : ipmi_monitoring_sensor_bitmask_physical_security = 1 ;
pub const ipmi_monitoring_sensor_bitmask_physical_security_IPMI_MONITORING_SENSOR_BITMASK_PHYSICAL_SECURITY_DRIVE_BAY_INTRUSION : ipmi_monitoring_sensor_bitmask_physical_security = 2 ;
pub const ipmi_monitoring_sensor_bitmask_physical_security_IPMI_MONITORING_SENSOR_BITMASK_PHYSICAL_SECURITY_IO_CARD_INTRUSION : ipmi_monitoring_sensor_bitmask_physical_security = 4 ;
pub const ipmi_monitoring_sensor_bitmask_physical_security_IPMI_MONITORING_SENSOR_BITMASK_PHYSICAL_SECURITY_PROCESSOR_AREA_INTRUSION : ipmi_monitoring_sensor_bitmask_physical_security = 8 ;
pub const ipmi_monitoring_sensor_bitmask_physical_security_IPMI_MONITORING_SENSOR_BITMASK_PHYSICAL_SECURITY_LAN_LEASH_LOST : ipmi_monitoring_sensor_bitmask_physical_security = 16 ;
pub const ipmi_monitoring_sensor_bitmask_physical_security_IPMI_MONITORING_SENSOR_BITMASK_PHYSICAL_SECURITY_UNAUTHORIZED_DOCK_UNDOCK : ipmi_monitoring_sensor_bitmask_physical_security = 32 ;
pub const ipmi_monitoring_sensor_bitmask_physical_security_IPMI_MONITORING_SENSOR_BITMASK_PHYSICAL_SECURITY_FAN_AREA_INTRUSION : ipmi_monitoring_sensor_bitmask_physical_security = 64 ;
pub type ipmi_monitoring_sensor_bitmask_physical_security = u32;
pub const ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt_IPMI_MONITORING_SENSOR_BITMASK_PLATFORM_SECURITY_VIOLATION_ATTEMPT_SECURE_MODE_VIOLATION_ATTEMPT : ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt = 1 ;
pub const ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt_IPMI_MONITORING_SENSOR_BITMASK_PLATFORM_SECURITY_VIOLATION_ATTEMPT_PRE_BOOT_PASSWORD_VIOLATION_USER_PASSWORD : ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt = 2 ;
pub const ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt_IPMI_MONITORING_SENSOR_BITMASK_PLATFORM_SECURITY_VIOLATION_ATTEMPT_PRE_BOOT_PASSWORD_VIOLATION_ATTEMPT_SETUP_PASSWORD : ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt = 4 ;
pub const ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt_IPMI_MONITORING_SENSOR_BITMASK_PLATFORM_SECURITY_VIOLATION_ATTEMPT_PRE_BOOT_PASSWORD_VIOLATION_NETWORK_BOOT_PASSWORD : ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt = 8 ;
pub const ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt_IPMI_MONITORING_SENSOR_BITMASK_PLATFORM_SECURITY_VIOLATION_ATTEMPT_OTHER_PRE_BOOT_PASSWORD_VIOLATION : ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt = 16 ;
pub const ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt_IPMI_MONITORING_SENSOR_BITMASK_PLATFORM_SECURITY_VIOLATION_ATTEMPT_OUT_OF_BAND_ACCESS_PASSWORD_VIOLATION : ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt = 32 ;
pub type ipmi_monitoring_sensor_bitmask_platform_security_violation_attempt = u32;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_IERR:
    ipmi_monitoring_sensor_bitmask_processor = 1;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_THERMAL_TRIP : ipmi_monitoring_sensor_bitmask_processor = 2 ;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_FRB1_BIST_FAILURE : ipmi_monitoring_sensor_bitmask_processor = 4 ;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_FRB2_HANG_IN_POST_FAILURE : ipmi_monitoring_sensor_bitmask_processor = 8 ;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_FRB3_PROCESSOR_STARTUP_INITIALIZATION_FAILURE : ipmi_monitoring_sensor_bitmask_processor = 16 ;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_CONFIGURATION_ERROR : ipmi_monitoring_sensor_bitmask_processor = 32 ;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_SMBIOS_UNCORRECTABLE_CPU_COMPLEX_ERROR : ipmi_monitoring_sensor_bitmask_processor = 64 ;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_PROCESSOR_PRESENCE_DETECTED : ipmi_monitoring_sensor_bitmask_processor = 128 ;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_PROCESSOR_DISABLED : ipmi_monitoring_sensor_bitmask_processor = 256 ;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_TERMINATOR_PRESENCE_DETECTED : ipmi_monitoring_sensor_bitmask_processor = 512 ;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_PROCESSOR_AUTOMATICALLY_THROTTLED : ipmi_monitoring_sensor_bitmask_processor = 1024 ;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_MACHINE_CHECK_EXCEPTION : ipmi_monitoring_sensor_bitmask_processor = 2048 ;
pub const ipmi_monitoring_sensor_bitmask_processor_IPMI_MONITORING_SENSOR_BITMASK_PROCESSOR_CORRECTABLE_MACHINE_CHECK_ERROR : ipmi_monitoring_sensor_bitmask_processor = 4096 ;
pub type ipmi_monitoring_sensor_bitmask_processor = u32;
pub const ipmi_monitoring_sensor_bitmask_power_supply_IPMI_MONITORING_SENSOR_BITMASK_POWER_SUPPLY_PRESENCE_DETECTED : ipmi_monitoring_sensor_bitmask_power_supply = 1 ;
pub const ipmi_monitoring_sensor_bitmask_power_supply_IPMI_MONITORING_SENSOR_BITMASK_POWER_SUPPLY_POWER_SUPPLY_FAILURE_DETECTED : ipmi_monitoring_sensor_bitmask_power_supply = 2 ;
pub const ipmi_monitoring_sensor_bitmask_power_supply_IPMI_MONITORING_SENSOR_BITMASK_POWER_SUPPLY_PREDICTIVE_FAILURE : ipmi_monitoring_sensor_bitmask_power_supply = 4 ;
pub const ipmi_monitoring_sensor_bitmask_power_supply_IPMI_MONITORING_SENSOR_BITMASK_POWER_SUPPLY_POWER_SUPPLY_INPUT_LOST_AC_DC : ipmi_monitoring_sensor_bitmask_power_supply = 8 ;
pub const ipmi_monitoring_sensor_bitmask_power_supply_IPMI_MONITORING_SENSOR_BITMASK_POWER_SUPPLY_POWER_SUPPLY_INPUT_LOST_OR_OUT_OF_RANGE : ipmi_monitoring_sensor_bitmask_power_supply = 16 ;
pub const ipmi_monitoring_sensor_bitmask_power_supply_IPMI_MONITORING_SENSOR_BITMASK_POWER_SUPPLY_POWER_SUPPLY_INPUT_OUT_OF_RANGE_BUT_PRESENT : ipmi_monitoring_sensor_bitmask_power_supply = 32 ;
pub const ipmi_monitoring_sensor_bitmask_power_supply_IPMI_MONITORING_SENSOR_BITMASK_POWER_SUPPLY_CONFIGURATION_ERROR : ipmi_monitoring_sensor_bitmask_power_supply = 64 ;
pub const ipmi_monitoring_sensor_bitmask_power_supply_IPMI_MONITORING_SENSOR_BITMASK_POWER_SUPPLY_POWER_SUPPLY_INACTIVE : ipmi_monitoring_sensor_bitmask_power_supply = 128 ;
pub type ipmi_monitoring_sensor_bitmask_power_supply = u32;
pub const ipmi_monitoring_sensor_bitmask_power_unit_IPMI_MONITORING_SENSOR_BITMASK_POWER_UNIT_POWER_OFF_POWER_DOWN : ipmi_monitoring_sensor_bitmask_power_unit = 1 ;
pub const ipmi_monitoring_sensor_bitmask_power_unit_IPMI_MONITORING_SENSOR_BITMASK_POWER_UNIT_POWER_CYCLE : ipmi_monitoring_sensor_bitmask_power_unit = 2 ;
pub const ipmi_monitoring_sensor_bitmask_power_unit_IPMI_MONITORING_SENSOR_BITMASK_POWER_UNIT_240VA_POWER_DOWN : ipmi_monitoring_sensor_bitmask_power_unit = 4 ;
pub const ipmi_monitoring_sensor_bitmask_power_unit_IPMI_MONITORING_SENSOR_BITMASK_POWER_UNIT_INTERLOCK_POWER_DOWN : ipmi_monitoring_sensor_bitmask_power_unit = 8 ;
pub const ipmi_monitoring_sensor_bitmask_power_unit_IPMI_MONITORING_SENSOR_BITMASK_POWER_UNIT_AC_LOST : ipmi_monitoring_sensor_bitmask_power_unit = 16 ;
pub const ipmi_monitoring_sensor_bitmask_power_unit_IPMI_MONITORING_SENSOR_BITMASK_POWER_UNIT_SOFT_POWER_CONTROL_FAILURE : ipmi_monitoring_sensor_bitmask_power_unit = 32 ;
pub const ipmi_monitoring_sensor_bitmask_power_unit_IPMI_MONITORING_SENSOR_BITMASK_POWER_UNIT_POWER_UNIT_FAILURE_DETECTED : ipmi_monitoring_sensor_bitmask_power_unit = 64 ;
pub const ipmi_monitoring_sensor_bitmask_power_unit_IPMI_MONITORING_SENSOR_BITMASK_POWER_UNIT_PREDICTIVE_FAILURE : ipmi_monitoring_sensor_bitmask_power_unit = 128 ;
pub type ipmi_monitoring_sensor_bitmask_power_unit = u32;
pub const ipmi_monitoring_sensor_bitmask_memory_IPMI_MONITORING_SENSOR_BITMASK_MEMORY_CORRECTABLE_MEMORY_ERROR : ipmi_monitoring_sensor_bitmask_memory = 1 ;
pub const ipmi_monitoring_sensor_bitmask_memory_IPMI_MONITORING_SENSOR_BITMASK_MEMORY_UNCORRECTABLE_MEMORY_ERROR : ipmi_monitoring_sensor_bitmask_memory = 2 ;
pub const ipmi_monitoring_sensor_bitmask_memory_IPMI_MONITORING_SENSOR_BITMASK_MEMORY_PARITY:
    ipmi_monitoring_sensor_bitmask_memory = 4;
pub const ipmi_monitoring_sensor_bitmask_memory_IPMI_MONITORING_SENSOR_BITMASK_MEMORY_MEMORY_SCRUB_FAILED : ipmi_monitoring_sensor_bitmask_memory = 8 ;
pub const ipmi_monitoring_sensor_bitmask_memory_IPMI_MONITORING_SENSOR_BITMASK_MEMORY_MEMORY_DEVICE_DISABLED : ipmi_monitoring_sensor_bitmask_memory = 16 ;
pub const ipmi_monitoring_sensor_bitmask_memory_IPMI_MONITORING_SENSOR_BITMASK_MEMORY_CORRECTABLE_MEMORY_ERROR_LOGGING_LIMIT_REACHED : ipmi_monitoring_sensor_bitmask_memory = 32 ;
pub const ipmi_monitoring_sensor_bitmask_memory_IPMI_MONITORING_SENSOR_BITMASK_MEMORY_PRESENCE_DETECTED : ipmi_monitoring_sensor_bitmask_memory = 64 ;
pub const ipmi_monitoring_sensor_bitmask_memory_IPMI_MONITORING_SENSOR_BITMASK_MEMORY_CONFIGURATION_ERROR : ipmi_monitoring_sensor_bitmask_memory = 128 ;
pub const ipmi_monitoring_sensor_bitmask_memory_IPMI_MONITORING_SENSOR_BITMASK_MEMORY_SPARE:
    ipmi_monitoring_sensor_bitmask_memory = 256;
pub const ipmi_monitoring_sensor_bitmask_memory_IPMI_MONITORING_SENSOR_BITMASK_MEMORY_MEMORY_AUTOMATICALLY_THROTTLED : ipmi_monitoring_sensor_bitmask_memory = 512 ;
pub const ipmi_monitoring_sensor_bitmask_memory_IPMI_MONITORING_SENSOR_BITMASK_MEMORY_CRITICAL_OVERTEMPERATURE : ipmi_monitoring_sensor_bitmask_memory = 1024 ;
pub type ipmi_monitoring_sensor_bitmask_memory = u32;
pub const ipmi_monitoring_sensor_bitmask_drive_slot_IPMI_MONITORING_SENSOR_BITMASK_DRIVE_SLOT_DRIVE_PRESENCE : ipmi_monitoring_sensor_bitmask_drive_slot = 1 ;
pub const ipmi_monitoring_sensor_bitmask_drive_slot_IPMI_MONITORING_SENSOR_BITMASK_DRIVE_SLOT_DRIVE_FAULT : ipmi_monitoring_sensor_bitmask_drive_slot = 2 ;
pub const ipmi_monitoring_sensor_bitmask_drive_slot_IPMI_MONITORING_SENSOR_BITMASK_DRIVE_SLOT_PREDICTIVE_FAILURE : ipmi_monitoring_sensor_bitmask_drive_slot = 4 ;
pub const ipmi_monitoring_sensor_bitmask_drive_slot_IPMI_MONITORING_SENSOR_BITMASK_DRIVE_SLOT_HOT_SPARE : ipmi_monitoring_sensor_bitmask_drive_slot = 8 ;
pub const ipmi_monitoring_sensor_bitmask_drive_slot_IPMI_MONITORING_SENSOR_BITMASK_DRIVE_SLOT_CONSISTENCY_CHECK_PARITY_CHECK_IN_PROGRESS : ipmi_monitoring_sensor_bitmask_drive_slot = 16 ;
pub const ipmi_monitoring_sensor_bitmask_drive_slot_IPMI_MONITORING_SENSOR_BITMASK_DRIVE_SLOT_IN_CRITICAL_ARRAY : ipmi_monitoring_sensor_bitmask_drive_slot = 32 ;
pub const ipmi_monitoring_sensor_bitmask_drive_slot_IPMI_MONITORING_SENSOR_BITMASK_DRIVE_SLOT_IN_FAILED_ARRAY : ipmi_monitoring_sensor_bitmask_drive_slot = 64 ;
pub const ipmi_monitoring_sensor_bitmask_drive_slot_IPMI_MONITORING_SENSOR_BITMASK_DRIVE_SLOT_REBUILD_REMAP_IN_PROGRESS : ipmi_monitoring_sensor_bitmask_drive_slot = 128 ;
pub const ipmi_monitoring_sensor_bitmask_drive_slot_IPMI_MONITORING_SENSOR_BITMASK_DRIVE_SLOT_REBUILD_REMAP_ABORTED : ipmi_monitoring_sensor_bitmask_drive_slot = 256 ;
pub type ipmi_monitoring_sensor_bitmask_drive_slot = u32;
pub const ipmi_monitoring_sensor_bitmask_system_firmware_progress_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_FIRMWARE_PROGRESS_SYSTEM_FIRMWARE_ERROR : ipmi_monitoring_sensor_bitmask_system_firmware_progress = 1 ;
pub const ipmi_monitoring_sensor_bitmask_system_firmware_progress_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_FIRMWARE_PROGRESS_SYSTEM_FIRMWARE_HANG : ipmi_monitoring_sensor_bitmask_system_firmware_progress = 2 ;
pub const ipmi_monitoring_sensor_bitmask_system_firmware_progress_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_FIRMWARE_PROGRESS_SYSTEM_FIRMWARE_PROGRESS : ipmi_monitoring_sensor_bitmask_system_firmware_progress = 4 ;
pub type ipmi_monitoring_sensor_bitmask_system_firmware_progress = u32;
pub const ipmi_monitoring_sensor_bitmask_event_logging_disabled_IPMI_MONITORING_SENSOR_BITMASK_EVENT_LOGGING_DISABLED_CORRECTABLE_MEMORY_ERROR_LOGGING_DISABLED : ipmi_monitoring_sensor_bitmask_event_logging_disabled = 1 ;
pub const ipmi_monitoring_sensor_bitmask_event_logging_disabled_IPMI_MONITORING_SENSOR_BITMASK_EVENT_LOGGING_DISABLED_EVENT_TYPE_LOGGING_DISABLED : ipmi_monitoring_sensor_bitmask_event_logging_disabled = 2 ;
pub const ipmi_monitoring_sensor_bitmask_event_logging_disabled_IPMI_MONITORING_SENSOR_BITMASK_EVENT_LOGGING_DISABLED_LOG_AREA_RESET_CLEARED : ipmi_monitoring_sensor_bitmask_event_logging_disabled = 4 ;
pub const ipmi_monitoring_sensor_bitmask_event_logging_disabled_IPMI_MONITORING_SENSOR_BITMASK_EVENT_LOGGING_DISABLED_ALL_EVENT_LOGGING_DISABLED : ipmi_monitoring_sensor_bitmask_event_logging_disabled = 8 ;
pub const ipmi_monitoring_sensor_bitmask_event_logging_disabled_IPMI_MONITORING_SENSOR_BITMASK_EVENT_LOGGING_DISABLED_SEL_FULL : ipmi_monitoring_sensor_bitmask_event_logging_disabled = 16 ;
pub const ipmi_monitoring_sensor_bitmask_event_logging_disabled_IPMI_MONITORING_SENSOR_BITMASK_EVENT_LOGGING_DISABLED_SEL_ALMOST_FULL : ipmi_monitoring_sensor_bitmask_event_logging_disabled = 32 ;
pub const ipmi_monitoring_sensor_bitmask_event_logging_disabled_IPMI_MONITORING_SENSOR_BITMASK_EVENT_LOGGING_DISABLED_CORRECTABLE_MACHINE_CHECK_ERROR_LOGGING_DISABLED : ipmi_monitoring_sensor_bitmask_event_logging_disabled = 64 ;
pub type ipmi_monitoring_sensor_bitmask_event_logging_disabled = u32;
pub const ipmi_monitoring_sensor_bitmask_watchdog1_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG1_BIOS_WATCHDOG_RESET : ipmi_monitoring_sensor_bitmask_watchdog1 = 1 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog1_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG1_OS_WATCHDOG_RESET : ipmi_monitoring_sensor_bitmask_watchdog1 = 2 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog1_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG1_OS_WATCHDOG_SHUT_DOWN : ipmi_monitoring_sensor_bitmask_watchdog1 = 4 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog1_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG1_OS_WATCHDOG_POWER_DOWN : ipmi_monitoring_sensor_bitmask_watchdog1 = 8 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog1_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG1_OS_WATCHDOG_POWER_CYCLE : ipmi_monitoring_sensor_bitmask_watchdog1 = 16 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog1_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG1_OS_WATCHDOG_NMI_DIAGNOSTIC_INTERRUPT : ipmi_monitoring_sensor_bitmask_watchdog1 = 32 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog1_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG1_OS_WATCHDOG_EXPIRED_STATUS_ONLY : ipmi_monitoring_sensor_bitmask_watchdog1 = 64 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog1_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG1_OS_WATCHDOG_PRE_TIMEOUT_INTERRUPT_NON_NMI : ipmi_monitoring_sensor_bitmask_watchdog1 = 128 ;
pub type ipmi_monitoring_sensor_bitmask_watchdog1 = u32;
pub const ipmi_monitoring_sensor_bitmask_system_event_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_EVENT_SYSTEM_RECONFIGURED : ipmi_monitoring_sensor_bitmask_system_event = 1 ;
pub const ipmi_monitoring_sensor_bitmask_system_event_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_EVENT_OEM_SYSTEM_BOOT_EVENT : ipmi_monitoring_sensor_bitmask_system_event = 2 ;
pub const ipmi_monitoring_sensor_bitmask_system_event_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_EVENT_UNDETERMINED_SYSTEM_HARDWARE_FAILURE : ipmi_monitoring_sensor_bitmask_system_event = 4 ;
pub const ipmi_monitoring_sensor_bitmask_system_event_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_EVENT_ENTRY_ADDED_TO_AUXILIARY_LOG : ipmi_monitoring_sensor_bitmask_system_event = 8 ;
pub const ipmi_monitoring_sensor_bitmask_system_event_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_EVENT_PEF_ACTION : ipmi_monitoring_sensor_bitmask_system_event = 16 ;
pub const ipmi_monitoring_sensor_bitmask_system_event_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_EVENT_TIMESTAMP_CLOCK_SYNC : ipmi_monitoring_sensor_bitmask_system_event = 32 ;
pub type ipmi_monitoring_sensor_bitmask_system_event = u32;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_FRONT_PANEL_NMI_DIAGNOSTIC_INTERRUPT : ipmi_monitoring_sensor_bitmask_critical_interrupt = 1 ;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_BUS_TIMEOUT : ipmi_monitoring_sensor_bitmask_critical_interrupt = 2 ;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_IO_CHANNEL_CHECK_NMI : ipmi_monitoring_sensor_bitmask_critical_interrupt = 4 ;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_SOFTWARE_NMI : ipmi_monitoring_sensor_bitmask_critical_interrupt = 8 ;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_PCI_PERR : ipmi_monitoring_sensor_bitmask_critical_interrupt = 16 ;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_PCI_SERR : ipmi_monitoring_sensor_bitmask_critical_interrupt = 32 ;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_EISA_FAIL_SAFE_TIMEOUT : ipmi_monitoring_sensor_bitmask_critical_interrupt = 64 ;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_BUS_CORRECTABLE_ERROR : ipmi_monitoring_sensor_bitmask_critical_interrupt = 128 ;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_BUS_UNCORRECTABLE_ERROR : ipmi_monitoring_sensor_bitmask_critical_interrupt = 256 ;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_FATAL_NMI : ipmi_monitoring_sensor_bitmask_critical_interrupt = 512 ;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_BUS_FATAL_ERROR : ipmi_monitoring_sensor_bitmask_critical_interrupt = 1024 ;
pub const ipmi_monitoring_sensor_bitmask_critical_interrupt_IPMI_MONITORING_SENSOR_BITMASK_CRITICAL_INTERRUPT_BUS_DEGRADED : ipmi_monitoring_sensor_bitmask_critical_interrupt = 2048 ;
pub type ipmi_monitoring_sensor_bitmask_critical_interrupt = u32;
pub const ipmi_monitoring_sensor_bitmask_button_switch_IPMI_MONITORING_SENSOR_BITMASK_BUTTON_SWITCH_POWER_BUTTON_PRESSED : ipmi_monitoring_sensor_bitmask_button_switch = 1 ;
pub const ipmi_monitoring_sensor_bitmask_button_switch_IPMI_MONITORING_SENSOR_BITMASK_BUTTON_SWITCH_SLEEP_BUTTON_PRESSED : ipmi_monitoring_sensor_bitmask_button_switch = 2 ;
pub const ipmi_monitoring_sensor_bitmask_button_switch_IPMI_MONITORING_SENSOR_BITMASK_BUTTON_SWITCH_RESET_BUTTON_PRESSED : ipmi_monitoring_sensor_bitmask_button_switch = 4 ;
pub const ipmi_monitoring_sensor_bitmask_button_switch_IPMI_MONITORING_SENSOR_BITMASK_BUTTON_SWITCH_FRU_LATCH_OPEN : ipmi_monitoring_sensor_bitmask_button_switch = 8 ;
pub const ipmi_monitoring_sensor_bitmask_button_switch_IPMI_MONITORING_SENSOR_BITMASK_BUTTON_SWITCH_FRU_SERVICE_REQUEST_BUTTON : ipmi_monitoring_sensor_bitmask_button_switch = 16 ;
pub type ipmi_monitoring_sensor_bitmask_button_switch = u32;
pub const ipmi_monitoring_sensor_bitmask_chip_set_IPMI_MONITORING_SENSOR_BITMASK_CHIP_SET_SOFT_POWER_CONTROL_FAILURE : ipmi_monitoring_sensor_bitmask_chip_set = 1 ;
pub const ipmi_monitoring_sensor_bitmask_chip_set_IPMI_MONITORING_SENSOR_BITMASK_CHIP_SET_THERMAL_TRIP : ipmi_monitoring_sensor_bitmask_chip_set = 2 ;
pub type ipmi_monitoring_sensor_bitmask_chip_set = u32;
pub const ipmi_monitoring_sensor_bitmask_cable_interconnect_IPMI_MONITORING_SENSOR_BITMASK_CABLE_INTERCONNECT_IS_CONNECTED : ipmi_monitoring_sensor_bitmask_cable_interconnect = 1 ;
pub const ipmi_monitoring_sensor_bitmask_cable_interconnect_IPMI_MONITORING_SENSOR_BITMASK_CABLE_INTERCONNECT_CONFIGURATION_ERROR : ipmi_monitoring_sensor_bitmask_cable_interconnect = 2 ;
pub type ipmi_monitoring_sensor_bitmask_cable_interconnect = u32;
pub const ipmi_monitoring_sensor_bitmask_system_boot_initiated_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_BOOT_INITIATED_INITIATED_BY_POWER_UP : ipmi_monitoring_sensor_bitmask_system_boot_initiated = 1 ;
pub const ipmi_monitoring_sensor_bitmask_system_boot_initiated_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_BOOT_INITIATED_INITIATED_BY_HARD_RESET : ipmi_monitoring_sensor_bitmask_system_boot_initiated = 2 ;
pub const ipmi_monitoring_sensor_bitmask_system_boot_initiated_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_BOOT_INITIATED_INITIATED_BY_WARM_RESET : ipmi_monitoring_sensor_bitmask_system_boot_initiated = 4 ;
pub const ipmi_monitoring_sensor_bitmask_system_boot_initiated_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_BOOT_INITIATED_USER_REQUESTED_PXE_BOOT : ipmi_monitoring_sensor_bitmask_system_boot_initiated = 8 ;
pub const ipmi_monitoring_sensor_bitmask_system_boot_initiated_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_BOOT_INITIATED_AUTOMATIC_BOOT_TO_DIAGNOSTIC : ipmi_monitoring_sensor_bitmask_system_boot_initiated = 16 ;
pub const ipmi_monitoring_sensor_bitmask_system_boot_initiated_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_BOOT_INITIATED_OS_RUN_TIME_SOFTWARE_INITIATED_HARD_RESET : ipmi_monitoring_sensor_bitmask_system_boot_initiated = 32 ;
pub const ipmi_monitoring_sensor_bitmask_system_boot_initiated_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_BOOT_INITIATED_OS_RUN_TIME_SOFTWARE_INITIATED_WARM_RESET : ipmi_monitoring_sensor_bitmask_system_boot_initiated = 64 ;
pub const ipmi_monitoring_sensor_bitmask_system_boot_initiated_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_BOOT_INITIATED_SYSTEM_RESTART : ipmi_monitoring_sensor_bitmask_system_boot_initiated = 128 ;
pub type ipmi_monitoring_sensor_bitmask_system_boot_initiated = u32;
pub const ipmi_monitoring_sensor_bitmask_boot_error_IPMI_MONITORING_SENSOR_BITMASK_BOOT_ERROR_NO_BOOTABLE_MEDIA : ipmi_monitoring_sensor_bitmask_boot_error = 1 ;
pub const ipmi_monitoring_sensor_bitmask_boot_error_IPMI_MONITORING_SENSOR_BITMASK_BOOT_ERROR_NON_BOOTABLE_DISKETTE_LEFT_IN_DRIVE : ipmi_monitoring_sensor_bitmask_boot_error = 2 ;
pub const ipmi_monitoring_sensor_bitmask_boot_error_IPMI_MONITORING_SENSOR_BITMASK_BOOT_ERROR_PXE_SERVER_NOT_FOUND : ipmi_monitoring_sensor_bitmask_boot_error = 4 ;
pub const ipmi_monitoring_sensor_bitmask_boot_error_IPMI_MONITORING_SENSOR_BITMASK_BOOT_ERROR_INVALID_BOOT_SECTOR : ipmi_monitoring_sensor_bitmask_boot_error = 8 ;
pub const ipmi_monitoring_sensor_bitmask_boot_error_IPMI_MONITORING_SENSOR_BITMASK_BOOT_ERROR_TIMEOUT_WAITING_FOR_USER_SELECTION_OF_BOOT_SOURCE : ipmi_monitoring_sensor_bitmask_boot_error = 16 ;
pub type ipmi_monitoring_sensor_bitmask_boot_error = u32;
pub const ipmi_monitoring_sensor_bitmask_os_boot_IPMI_MONITORING_SENSOR_BITMASK_OS_BOOT_A_BOOT_COMPLETED : ipmi_monitoring_sensor_bitmask_os_boot = 1 ;
pub const ipmi_monitoring_sensor_bitmask_os_boot_IPMI_MONITORING_SENSOR_BITMASK_OS_BOOT_C_BOOT_COMPLETED : ipmi_monitoring_sensor_bitmask_os_boot = 2 ;
pub const ipmi_monitoring_sensor_bitmask_os_boot_IPMI_MONITORING_SENSOR_BITMASK_OS_BOOT_PXE_BOOT_COMPLETED : ipmi_monitoring_sensor_bitmask_os_boot = 4 ;
pub const ipmi_monitoring_sensor_bitmask_os_boot_IPMI_MONITORING_SENSOR_BITMASK_OS_BOOT_DIAGNOSTIC_BOOT_COMPLETED : ipmi_monitoring_sensor_bitmask_os_boot = 8 ;
pub const ipmi_monitoring_sensor_bitmask_os_boot_IPMI_MONITORING_SENSOR_BITMASK_OS_BOOT_CD_ROM_BOOT_COMPLETED : ipmi_monitoring_sensor_bitmask_os_boot = 16 ;
pub const ipmi_monitoring_sensor_bitmask_os_boot_IPMI_MONITORING_SENSOR_BITMASK_OS_BOOT_ROM_BOOT_COMPLETED : ipmi_monitoring_sensor_bitmask_os_boot = 32 ;
pub const ipmi_monitoring_sensor_bitmask_os_boot_IPMI_MONITORING_SENSOR_BITMASK_OS_BOOT_BOOT_COMPLETED_BOOT_DEVICE_NOT_SPECIFIED : ipmi_monitoring_sensor_bitmask_os_boot = 64 ;
pub const ipmi_monitoring_sensor_bitmask_os_boot_IPMI_MONITORING_SENSOR_BITMASK_OS_BOOT_BASE_OS_HYPERVISOR_INSTALLATION_STARTED : ipmi_monitoring_sensor_bitmask_os_boot = 128 ;
pub const ipmi_monitoring_sensor_bitmask_os_boot_IPMI_MONITORING_SENSOR_BITMASK_OS_BOOT_BASE_OS_HYPERVISOR_INSTALLATION_COMPLETED : ipmi_monitoring_sensor_bitmask_os_boot = 256 ;
pub const ipmi_monitoring_sensor_bitmask_os_boot_IPMI_MONITORING_SENSOR_BITMASK_OS_BOOT_BASE_OS_HYPERVISOR_INSTALLATION_ABORTED : ipmi_monitoring_sensor_bitmask_os_boot = 512 ;
pub const ipmi_monitoring_sensor_bitmask_os_boot_IPMI_MONITORING_SENSOR_BITMASK_OS_BOOT_BASE_OS_HYPERVISOR_INSTALLATION_FAILED : ipmi_monitoring_sensor_bitmask_os_boot = 1024 ;
pub type ipmi_monitoring_sensor_bitmask_os_boot = u32;
pub const ipmi_monitoring_sensor_bitmask_os_critical_stop_IPMI_MONITORING_SENSOR_BITMASK_OS_CRITICAL_STOP_CRITICAL_STOP_DURING_OS_LOAD : ipmi_monitoring_sensor_bitmask_os_critical_stop = 1 ;
pub const ipmi_monitoring_sensor_bitmask_os_critical_stop_IPMI_MONITORING_SENSOR_BITMASK_OS_CRITICAL_STOP_RUN_TIME_CRITICAL_STOP : ipmi_monitoring_sensor_bitmask_os_critical_stop = 2 ;
pub const ipmi_monitoring_sensor_bitmask_os_critical_stop_IPMI_MONITORING_SENSOR_BITMASK_OS_CRITICAL_STOP_OS_GRACEFUL_STOP : ipmi_monitoring_sensor_bitmask_os_critical_stop = 4 ;
pub const ipmi_monitoring_sensor_bitmask_os_critical_stop_IPMI_MONITORING_SENSOR_BITMASK_OS_CRITICAL_STOP_OS_GRACEFUL_SHUTDOWN : ipmi_monitoring_sensor_bitmask_os_critical_stop = 8 ;
pub const ipmi_monitoring_sensor_bitmask_os_critical_stop_IPMI_MONITORING_SENSOR_BITMASK_OS_CRITICAL_STOP_SOFT_SHUTDOWN_INITIATED_BY_PEF : ipmi_monitoring_sensor_bitmask_os_critical_stop = 16 ;
pub const ipmi_monitoring_sensor_bitmask_os_critical_stop_IPMI_MONITORING_SENSOR_BITMASK_OS_CRITICAL_STOP_AGENT_NOT_RESPONDING : ipmi_monitoring_sensor_bitmask_os_critical_stop = 32 ;
pub type ipmi_monitoring_sensor_bitmask_os_critical_stop = u32;
pub const ipmi_monitoring_sensor_bitmask_slot_connector_IPMI_MONITORING_SENSOR_BITMASK_SLOT_CONNECTOR_FAULT_STATUS_ASSERTED : ipmi_monitoring_sensor_bitmask_slot_connector = 1 ;
pub const ipmi_monitoring_sensor_bitmask_slot_connector_IPMI_MONITORING_SENSOR_BITMASK_SLOT_CONNECTOR_IDENTIFY_STATUS_ASSERTED : ipmi_monitoring_sensor_bitmask_slot_connector = 2 ;
pub const ipmi_monitoring_sensor_bitmask_slot_connector_IPMI_MONITORING_SENSOR_BITMASK_SLOT_CONNECTOR_SLOT_CONNECTOR_DEVICE_INSTALLED_ATTACHED : ipmi_monitoring_sensor_bitmask_slot_connector = 4 ;
pub const ipmi_monitoring_sensor_bitmask_slot_connector_IPMI_MONITORING_SENSOR_BITMASK_SLOT_CONNECTOR_SLOT_CONNECTOR_READY_FOR_DEVICE_INSTALLATION : ipmi_monitoring_sensor_bitmask_slot_connector = 8 ;
pub const ipmi_monitoring_sensor_bitmask_slot_connector_IPMI_MONITORING_SENSOR_BITMASK_SLOT_CONNECTOR_SLOT_CONNECTOR_READY_FOR_DEVICE_REMOVAL : ipmi_monitoring_sensor_bitmask_slot_connector = 16 ;
pub const ipmi_monitoring_sensor_bitmask_slot_connector_IPMI_MONITORING_SENSOR_BITMASK_SLOT_CONNECTOR_SLOT_POWER_IS_OFF : ipmi_monitoring_sensor_bitmask_slot_connector = 32 ;
pub const ipmi_monitoring_sensor_bitmask_slot_connector_IPMI_MONITORING_SENSOR_BITMASK_SLOT_CONNECTOR_SLOT_CONNECTOR_DEVICE_REMOVAL_REQUEST : ipmi_monitoring_sensor_bitmask_slot_connector = 64 ;
pub const ipmi_monitoring_sensor_bitmask_slot_connector_IPMI_MONITORING_SENSOR_BITMASK_SLOT_CONNECTOR_INTERLOCK_ASSERTED : ipmi_monitoring_sensor_bitmask_slot_connector = 128 ;
pub const ipmi_monitoring_sensor_bitmask_slot_connector_IPMI_MONITORING_SENSOR_BITMASK_SLOT_CONNECTOR_SLOT_IS_DISABLED : ipmi_monitoring_sensor_bitmask_slot_connector = 256 ;
pub const ipmi_monitoring_sensor_bitmask_slot_connector_IPMI_MONITORING_SENSOR_BITMASK_SLOT_CONNECTOR_SLOT_HOLDS_SPARE_DEVICE : ipmi_monitoring_sensor_bitmask_slot_connector = 512 ;
pub type ipmi_monitoring_sensor_bitmask_slot_connector = u32;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_S0_G0 : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 1 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_S1 : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 2 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_S2 : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 4 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_S3 : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 8 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_S4 : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 16 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_S5_G2 : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 32 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_S4_S5_SOFT_OFF : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 64 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_G3_MECHANICAL_OFF : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 128 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_SLEEPING_IN_AN_S1_S2_OR_S3_STATES : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 256 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_G1_SLEEPING : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 512 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_S5_ENTERED_BY_OVERRIDE : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 1024 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_LEGACY_ON_STATE : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 2048 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_LEGACY_OFF_STATE : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 4096 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_UNSPECIFIED : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 8192 ;
pub const ipmi_monitoring_sensor_bitmask_system_acpi_power_state_IPMI_MONITORING_SENSOR_BITMASK_SYSTEM_ACPI_POWER_STATE_UNKNOWN : ipmi_monitoring_sensor_bitmask_system_acpi_power_state = 16384 ;
pub type ipmi_monitoring_sensor_bitmask_system_acpi_power_state = u32;
pub const ipmi_monitoring_sensor_bitmask_watchdog2_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG2_TIMER_EXPIRED : ipmi_monitoring_sensor_bitmask_watchdog2 = 1 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog2_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG2_HARD_RESET : ipmi_monitoring_sensor_bitmask_watchdog2 = 2 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog2_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG2_POWER_DOWN : ipmi_monitoring_sensor_bitmask_watchdog2 = 4 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog2_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG2_POWER_CYCLE : ipmi_monitoring_sensor_bitmask_watchdog2 = 8 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog2_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG2_RESERVED1 : ipmi_monitoring_sensor_bitmask_watchdog2 = 16 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog2_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG2_RESERVED2 : ipmi_monitoring_sensor_bitmask_watchdog2 = 32 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog2_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG2_RESERVED3 : ipmi_monitoring_sensor_bitmask_watchdog2 = 64 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog2_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG2_RESERVED4 : ipmi_monitoring_sensor_bitmask_watchdog2 = 128 ;
pub const ipmi_monitoring_sensor_bitmask_watchdog2_IPMI_MONITORING_SENSOR_BITMASK_WATCHDOG2_TIMER_INTERRUPT : ipmi_monitoring_sensor_bitmask_watchdog2 = 256 ;
pub type ipmi_monitoring_sensor_bitmask_watchdog2 = u32;
pub const ipmi_monitoring_sensor_bitmask_platform_alert_IPMI_MONITORING_SENSOR_BITMASK_PLATFORM_ALERT_PLATFORM_GENERATED_PAGE : ipmi_monitoring_sensor_bitmask_platform_alert = 1 ;
pub const ipmi_monitoring_sensor_bitmask_platform_alert_IPMI_MONITORING_SENSOR_BITMASK_PLATFORM_ALERT_PLATFORM_GENERATED_LAN_ALERT : ipmi_monitoring_sensor_bitmask_platform_alert = 2 ;
pub const ipmi_monitoring_sensor_bitmask_platform_alert_IPMI_MONITORING_SENSOR_BITMASK_PLATFORM_ALERT_PLATFORM_EVENT_TRAP_GENERATED : ipmi_monitoring_sensor_bitmask_platform_alert = 4 ;
pub const ipmi_monitoring_sensor_bitmask_platform_alert_IPMI_MONITORING_SENSOR_BITMASK_PLATFORM_ALERT_PLATFORM_GENERATED_SNMP_TRAP : ipmi_monitoring_sensor_bitmask_platform_alert = 8 ;
pub type ipmi_monitoring_sensor_bitmask_platform_alert = u32;
pub const ipmi_monitoring_sensor_bitmask_entity_presence_IPMI_MONITORING_SENSOR_BITMASK_ENTITY_PRESENCE_ENTITY_PRESENT : ipmi_monitoring_sensor_bitmask_entity_presence = 1 ;
pub const ipmi_monitoring_sensor_bitmask_entity_presence_IPMI_MONITORING_SENSOR_BITMASK_ENTITY_PRESENCE_ENTITY_ABSENT : ipmi_monitoring_sensor_bitmask_entity_presence = 2 ;
pub const ipmi_monitoring_sensor_bitmask_entity_presence_IPMI_MONITORING_SENSOR_BITMASK_ENTITY_PRESENCE_ENTITY_DISABLED : ipmi_monitoring_sensor_bitmask_entity_presence = 4 ;
pub type ipmi_monitoring_sensor_bitmask_entity_presence = u32;
pub const ipmi_monitoring_sensor_bitmask_lan_IPMI_MONITORING_SENSOR_BITMASK_LAN_HEARTBEAT_LOST:
    ipmi_monitoring_sensor_bitmask_lan = 1;
pub const ipmi_monitoring_sensor_bitmask_lan_IPMI_MONITORING_SENSOR_BITMASK_LAN_HEARTBEAT:
    ipmi_monitoring_sensor_bitmask_lan = 2;
pub type ipmi_monitoring_sensor_bitmask_lan = u32;
pub const ipmi_monitoring_sensor_bitmask_management_subsystem_health_IPMI_MONITORING_SENSOR_BITMASK_MANAGEMENT_SUBSYSTEM_HEALTH_SENSOR_ACCESS_DEGRADED_OR_UNAVAILABLE : ipmi_monitoring_sensor_bitmask_management_subsystem_health = 1 ;
pub const ipmi_monitoring_sensor_bitmask_management_subsystem_health_IPMI_MONITORING_SENSOR_BITMASK_MANAGEMENT_SUBSYSTEM_HEALTH_CONTROLLER_ACCESS_DEGRADED_OR_UNAVAILABLE : ipmi_monitoring_sensor_bitmask_management_subsystem_health = 2 ;
pub const ipmi_monitoring_sensor_bitmask_management_subsystem_health_IPMI_MONITORING_SENSOR_BITMASK_MANAGEMENT_SUBSYSTEM_HEALTH_MANAGEMENT_CONTROLLER_OFF_LINE : ipmi_monitoring_sensor_bitmask_management_subsystem_health = 4 ;
pub const ipmi_monitoring_sensor_bitmask_management_subsystem_health_IPMI_MONITORING_SENSOR_BITMASK_MANAGEMENT_SUBSYSTEM_HEALTH_MANAGEMENT_CONTROLLER_UNAVAILABLE : ipmi_monitoring_sensor_bitmask_management_subsystem_health = 8 ;
pub const ipmi_monitoring_sensor_bitmask_management_subsystem_health_IPMI_MONITORING_SENSOR_BITMASK_MANAGEMENT_SUBSYSTEM_HEALTH_SENSOR_FAILURE : ipmi_monitoring_sensor_bitmask_management_subsystem_health = 16 ;
pub const ipmi_monitoring_sensor_bitmask_management_subsystem_health_IPMI_MONITORING_SENSOR_BITMASK_MANAGEMENT_SUBSYSTEM_HEALTH_FRU_FAILURE : ipmi_monitoring_sensor_bitmask_management_subsystem_health = 32 ;
pub type ipmi_monitoring_sensor_bitmask_management_subsystem_health = u32;
pub const ipmi_monitoring_sensor_bitmask_battery_IPMI_MONITORING_SENSOR_BITMASK_BATTERY_BATTERY_LOW : ipmi_monitoring_sensor_bitmask_battery = 1 ;
pub const ipmi_monitoring_sensor_bitmask_battery_IPMI_MONITORING_SENSOR_BITMASK_BATTERY_BATTERY_FAILED : ipmi_monitoring_sensor_bitmask_battery = 2 ;
pub const ipmi_monitoring_sensor_bitmask_battery_IPMI_MONITORING_SENSOR_BITMASK_BATTERY_BATTERY_PRESENCE_DETECTED : ipmi_monitoring_sensor_bitmask_battery = 4 ;
pub type ipmi_monitoring_sensor_bitmask_battery = u32;
pub const ipmi_monitoring_sensor_bitmask_session_audit_IPMI_MONITORING_SENSOR_BITMASK_SESSION_AUDIT_SESSION_ACTIVATED : ipmi_monitoring_sensor_bitmask_session_audit = 1 ;
pub const ipmi_monitoring_sensor_bitmask_session_audit_IPMI_MONITORING_SENSOR_BITMASK_SESSION_AUDIT_SESSION_DEACTIVATED : ipmi_monitoring_sensor_bitmask_session_audit = 2 ;
pub const ipmi_monitoring_sensor_bitmask_session_audit_IPMI_MONITORING_SENSOR_BITMASK_SESSION_AUDIT_INVALID_USERNAME_OR_PASSWORD : ipmi_monitoring_sensor_bitmask_session_audit = 4 ;
pub const ipmi_monitoring_sensor_bitmask_session_audit_IPMI_MONITORING_SENSOR_BITMASK_SESSION_AUDIT_INVALID_PASSWORD_DISABLE : ipmi_monitoring_sensor_bitmask_session_audit = 8 ;
pub type ipmi_monitoring_sensor_bitmask_session_audit = u32;
pub const ipmi_monitoring_sensor_bitmask_version_change_IPMI_MONITORING_SENSOR_BITMASK_VERSION_CHANGE_HARDWARE_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY : ipmi_monitoring_sensor_bitmask_version_change = 1 ;
pub const ipmi_monitoring_sensor_bitmask_version_change_IPMI_MONITORING_SENSOR_BITMASK_VERSION_CHANGE_FIRMWARE_OR_SOFTWARE_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY : ipmi_monitoring_sensor_bitmask_version_change = 2 ;
pub const ipmi_monitoring_sensor_bitmask_version_change_IPMI_MONITORING_SENSOR_BITMASK_VERSION_CHANGE_HARDWARE_INCOMPATABILITY_DETECTED_WITH_ASSOCIATED_ENTITY : ipmi_monitoring_sensor_bitmask_version_change = 4 ;
pub const ipmi_monitoring_sensor_bitmask_version_change_IPMI_MONITORING_SENSOR_BITMASK_VERSION_CHANGE_FIRMWARE_OR_SOFTWARE_INCOMPATABILITY_DETECTED_WITH_ASSOCIATED_ENTITY : ipmi_monitoring_sensor_bitmask_version_change = 8 ;
pub const ipmi_monitoring_sensor_bitmask_version_change_IPMI_MONITORING_SENSOR_BITMASK_VERSION_CHANGE_ENTITY_IS_OF_AN_INVALID_OR_UNSUPPORTED_HARDWARE_VERSION : ipmi_monitoring_sensor_bitmask_version_change = 16 ;
pub const ipmi_monitoring_sensor_bitmask_version_change_IPMI_MONITORING_SENSOR_BITMASK_VERSION_CHANGE_ENTITY_CONTAINS_AN_INVALID_OR_UNSUPPORTED_FIRMWARE_OR_SOFTWARE_VERSION : ipmi_monitoring_sensor_bitmask_version_change = 32 ;
pub const ipmi_monitoring_sensor_bitmask_version_change_IPMI_MONITORING_SENSOR_BITMASK_VERSION_CHANGE_HARDWARE_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY_WAS_SUCCESSFUL : ipmi_monitoring_sensor_bitmask_version_change = 64 ;
pub const ipmi_monitoring_sensor_bitmask_version_change_IPMI_MONITORING_SENSOR_BITMASK_VERSION_CHANGE_SOFTWARE_OR_FW_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY_WAS_SUCCESSFUL : ipmi_monitoring_sensor_bitmask_version_change = 128 ;
pub type ipmi_monitoring_sensor_bitmask_version_change = u32;
pub const ipmi_monitoring_sensor_bitmask_fru_state_IPMI_MONITORING_SENSOR_BITMASK_FRU_STATE_FRU_NOT_INSTALLED : ipmi_monitoring_sensor_bitmask_fru_state = 1 ;
pub const ipmi_monitoring_sensor_bitmask_fru_state_IPMI_MONITORING_SENSOR_BITMASK_FRU_STATE_FRU_INACTIVE : ipmi_monitoring_sensor_bitmask_fru_state = 2 ;
pub const ipmi_monitoring_sensor_bitmask_fru_state_IPMI_MONITORING_SENSOR_BITMASK_FRU_STATE_FRU_ACTIVATION_REQUESTED : ipmi_monitoring_sensor_bitmask_fru_state = 4 ;
pub const ipmi_monitoring_sensor_bitmask_fru_state_IPMI_MONITORING_SENSOR_BITMASK_FRU_STATE_FRU_ACTIVATION_IN_PROGRESS : ipmi_monitoring_sensor_bitmask_fru_state = 8 ;
pub const ipmi_monitoring_sensor_bitmask_fru_state_IPMI_MONITORING_SENSOR_BITMASK_FRU_STATE_FRU_ACTIVE : ipmi_monitoring_sensor_bitmask_fru_state = 16 ;
pub const ipmi_monitoring_sensor_bitmask_fru_state_IPMI_MONITORING_SENSOR_BITMASK_FRU_STATE_FRU_DEACTIVATION_REQUESTED : ipmi_monitoring_sensor_bitmask_fru_state = 32 ;
pub const ipmi_monitoring_sensor_bitmask_fru_state_IPMI_MONITORING_SENSOR_BITMASK_FRU_STATE_FRU_DEACTIVATION_IN_PROGRESS : ipmi_monitoring_sensor_bitmask_fru_state = 64 ;
pub const ipmi_monitoring_sensor_bitmask_fru_state_IPMI_MONITORING_SENSOR_BITMASK_FRU_STATE_FRU_COMMUNICATION_LOST : ipmi_monitoring_sensor_bitmask_fru_state = 128 ;
pub type ipmi_monitoring_sensor_bitmask_fru_state = u32;
